"""empty message

Revision ID: db38787cc56f
Revises: 
Create Date: 2021-06-03 14:56:33.368298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db38787cc56f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aluno',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('cpf', sa.String(length=50), nullable=False),
    sa.Column('dre', sa.String(length=50), nullable=False),
    sa.Column('curso', sa.String(length=50), nullable=False),
    sa.Column('senha_hash', sa.String(length=280), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('dre'),
    sa.UniqueConstraint('email')
    )
    op.create_table('criar_disciplina',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('materia', sa.String(length=50), nullable=False),
    sa.Column('professor', sa.String(length=50), nullable=False),
    sa.Column('periodo', sa.String(length=50), nullable=False),
    sa.Column('codigo_materia', sa.String(length=5), nullable=False),
    sa.Column('codigo_turma', sa.String(length=5), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo_materia'),
    sa.UniqueConstraint('codigo_turma')
    )
    op.create_table('login',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cpf', sa.String(length=50), nullable=False),
    sa.Column('senha_hash', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('professor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('cpf', sa.String(length=50), nullable=False),
    sa.Column('siape', sa.String(length=50), nullable=False),
    sa.Column('senha_hash', sa.LargeBinary(length=280), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('siape')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('professor')
    op.drop_table('login')
    op.drop_table('criar_disciplina')
    op.drop_table('aluno')
    # ### end Alembic commands ###
